# Generated by Django 5.2.14 on 2026-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, unique=True)),
                ('driver_name', models.CharField(max_length=120)),
                ('driver_phone', models.CharField(max_length=15)),
                ('current_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPATCHED', 'Dispatched'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
